services:
  app:
    tty: true
    build:
      context: ./
      dockerfile: Dockerfile-dev
    env_file:
      - .env
    volumes:
      - ./:/var/www/app
      - app_node_modules:/var/www/app/node_modules
    ports:
      - 5173:5173
      - 24678:24678
    command: ['sh', '-c', 'pnpm install && pnpm start:dev']

volumes:
  app_node_modules:
