FROM node:20-bookworm

ENV npm_config_update_notifier=false \
    npm_config_fund=false

RUN npm install -g pnpm@10.30.3

ENV NODE_ENV development

# set working directory
RUN mkdir -p /var/www/app \
  && chown -R node:node /var/www/app

WORKDIR /var/www/app

EXPOSE 3000
