name: Run checks and tests

on: workflow_call

jobs:
  validate-markdown:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      contents: read
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js and restore pnpm cache
        uses: ./.github/actions/setup-nodejs-and-restore-pnpm-cache

      - name: Validate markdown authors and posts
        id: validate_markdown
        run: CI=true pnpm validate-markdown

      - name: Add a comment to the PR after failed markdown validation
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && failure()
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          header: validate-markdown
          message: |
            #### Markdown invalid 🖌

            The markdown of the file **${{ steps.validate_markdown.outputs.filePath }}** is invalid !
            > ${{ steps.validate_markdown.outputs.reason }}

      - name: Remove a comment to the PR after success markdown validation
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request' && success()
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          number: ${{ github.event.pull_request.number }}
          header: validate-markdown
          delete: true

  eslint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js and restore pnpm cache
        uses: ./.github/actions/setup-nodejs-and-restore-pnpm-cache

      - name: Lint code
        run: pnpm lint

  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js and restore pnpm cache
        uses: ./.github/actions/setup-nodejs-and-restore-pnpm-cache

      - name: Run TypeScript type-check
        run: pnpm type-check

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js and restore pnpm cache
        uses: ./.github/actions/setup-nodejs-and-restore-pnpm-cache

      - name: Run Tests
        run: pnpm test

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup Node.js and restore pnpm cache
        uses: ./.github/actions/setup-nodejs-and-restore-pnpm-cache

      - name: Build Application
        run: WITH_DOWNLOAD_TRANSLATIONS_AND_GENERATE_IMAGE_FORMATS=false pnpm build
